<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

- Subsetting means to ‘select’.
- Indexing refers to selecting one element.
- Slicing refers to selecting a range of elements.

# 1 Subsetting: Indexing and Slicing

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
#x = np_array

In [5]:
x[2]

'c3'

In [7]:
x[2:4]
# Remember slicing in Python can be a bit tricky.
If you slice with [i:j], the slice will start at i and end at j-1, giving you a total of j-i elements.

['c3', 'd4']

In [8]:
x[2:8:2]

['c3', 'e5', 'g7']

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

In [9]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [10]:
np_array[my_mask] # give all the True numbers 

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
my_mask.sum() # True =1, False =0, 7 means the sum of all the True / False statements -> 7 True

np.int64(7)

In [11]:
np_array[np_array > 3] # more succinct way, no need to create another new variable

array([ 4,  5,  6,  7,  8,  9, 10])

In [12]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [15]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [18]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [19]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [20]:
py_list_2d[3]

[4, 'D']

In [21]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [23]:
py_list_2d[3][0]

4

In [24]:
np_array_2d[3, 0]

np.str_('4')

In [25]:
x = [[[1,2],[3,4]],[[2,2],[3,4]],[[3,2],[3,4]]] #this is a 3D array
x[0][1][1]

np_x = np.array(x)

In [26]:
np_x[0,1,1]

np.int64(4)

## 1.4 Growing lists

In [2]:
x =[1]
x =x + [1]

x= x+ [2]

x=x + [3]

x

[1, 1, 2, 3]

In [3]:
x=[1]
x +=[1]
x +=[2]
x +=[3]
x

[1, 1, 2, 3]

In [4]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [6]:
x=[1]
x.append([2]) 
x.append(3)
x.append(4)
x
#append runs faster as compared to the normal way of adding stuff to the list

[1, [2], 3, 4]

In [7]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x
#extend joins two lists together 

[1, 2, 3, 4, 5, 6]

In [11]:
x=[1, 2, 3]
x.append([4, 5, 6])
x
#append just adds whatever in the bracket to the original list

[1, 2, 3, [4, 5, 6]]

In [12]:
x=[1, 2, 3]
x.insert(1, '0')             #insert(index of the thing, the thing inserted)
x

[1, '0', 2, 3]

# Some loose ends

## 1.5 Tuples

In [14]:
aa =[1, 2, 3]
aa[0] = 1234
aa

[1234, 2, 3]

In [13]:
a=(1, 2, 3)     # Define tuple

In [15]:
#this will not work, cannot change data in tuple
a[0]=1234

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [16]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [18]:
y[0]=1234

In [19]:
print(f'{x=}, {y=}, {z=}')

x=[1234, 2, 3], y=[1234, 2, 3], z=[1234, 2, 3]


In [ ]:
#correct way to do this:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Footnotes